[package]
name = "hyperlight"
version = "0.0.1"
edition = "2024"

[dependencies]
anyhow = "1.0"
codegen_api = { path = "./codegen_api" }
inkwell = { version = "0.6", features = ["llvm18-1-prefer-dynamic"] }

[workspace]
members = ["codegen_api"]
